export const LOGIN_USER_RECEIVED = "LOGIN_USER_RECEIVED";

export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";

export const LOGOUT_USER_RECEIVED = "LOGOUT_USER_RECEIVED";

export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";

export const ADD_USER_RECEIVED = "ADD_USER_RECEIVED";

export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const FETCH_RIDE_REQUEST = "FETCH_RIDE_REQUEST";

export const FETCH_RIDE_RECEIVED ="FETCH_RIDE_RECEIVED";

export const FETCH_RIDE_FAILED ="FETCH_RIDE_FAILED";

export const OFFER_RIDE_REQUEST ="OFFER_RIDE_REQUEST";

export const OFFER_RIDE_RECEIVED ="OFFER_RIDE_RECEIVED";

export const OFFER_RIDE_FAILED ="OFFER_RIDE_FAILED";

export const BOOK_RIDE_REQUEST ="BOOK_RIDE_REQUEST";

export const BOOK_RIDE_RECEIVED ="BOOK_RIDE_RECEIVED";

export const BOOK_RIDE_FAILED ="BOOK_RIDE_FAILED";

export const CANCEL_RIDE_REQUEST ="CANCEL_RIDE_REQUEST";

export const CANCEL_RIDE_RECEIVED ="CANCEL_RIDE_RECEIVED";

export const CANCEL_RIDE_FAILED ="CANCEL_RIDE_FAILED";